services:
  _defaults:
    autoconfigure: true

  Elbformat\SuluBehatBundle\Context\AbstractSuluContext:
    abstract: true
    arguments:
      $entityManager: '@doctrine.orm.entity_manager'
      $webspaceManager: '@sulu_core.webspace.webspace_manager'

  Elbformat\SuluBehatBundle\Context\SuluAdminContext:
    arguments:
      $state: '@Elbformat\SymfonyBehatBundle\Browser\State'
      $kernel: '@kernel'

  Elbformat\SuluBehatBundle\Context\SuluArticleContext:
    parent: Elbformat\SuluBehatBundle\Context\AbstractSuluContext
    arguments:
      $messageBus: '@sulu_message_bus'
      $articleRepository: '@sulu_article.article_repository'

  Elbformat\SuluBehatBundle\Context\SuluMediaContext:
    parent: Elbformat\SuluBehatBundle\Context\AbstractSuluContext
    arguments:
      $mediaManager: '@sulu_media.media_manager'
      $collectionManager: '@sulu_media.collection_manager'
      $projectDir: '%kernel.project_dir%'

  Elbformat\SuluBehatBundle\Context\SuluPageContext:
    parent: Elbformat\SuluBehatBundle\Context\AbstractSuluContext
    arguments:
      $messageBus: '@sulu_message_bus'
      $pageRepository: '@sulu_page.page_repository'
      $routeRepository: '@sulu_route.route_repository'

  Elbformat\SuluBehatBundle\Context\SuluSnippetContext:
    parent: Elbformat\SuluBehatBundle\Context\AbstractSuluContext
    arguments:
      $messageBus: '@sulu_message_bus'
      $snippetRepository: '@sulu_snippet.snippet_repository'

  # Test double
  Elbformat\SuluBehatBundle\Sulu\DateTimeRequestProcessor:
    decorates: 'sulu_core.request_processor.date_time'
    tags:
      - { name: 'sulu.context', context: "website" }
