services:
#  _defaults:
#    autowire: true
#    autoconfigure: true

#  Elbformat\SuluBehatBundle\Context\:
#    resource: '../../Context/*Context.php'
#    # Dependencies must be checked first -> Will be done in DI Extension
#    exclude:
#      - '../../Context/SuluArticleContext.php'
#      - '../../Context/SuluCommunityContext.php'
#      - '../../Context/SuluFormContext.php'

  Elbformat\SuluBehatBundle\Context\SuluPageContext:
      arguments:
        $pageRepository: '@sulu_page.page_repository'
        $messageBus: '@sulu_message_bus'

#  Elbformat\SuluBehatBundle\Context\SuluAdminContext:
#    arguments:
#      $state: '@Elbformat\SymfonyBehatBundle\Browser\State'
#
#  Elbformat\SuluBehatBundle\Context\SuluMediaContext:
#    arguments:
#      $projectDir: '%kernel.project_dir%'

  # Test double
  Elbformat\SuluBehatBundle\Sulu\DateTimeRequestProcessor:
    decorates: 'sulu_core.request_processor.date_time'
    tags:
      - { name: 'sulu.context', context: "website" }
