FROM php:8.4-alpine3.24
LABEL org.opencontainers.image.source="https://github.com/elbformat/sulu-behat-bundle"

# opcache
RUN docker-php-ext-install opcache

# ext-intl
#RUN apk add --no-cache icu icu-data-full && \
#    apk add --no-cache --virtual .build-deps icu-dev && \
#    docker-php-ext-install intl  && \
#    apk del .build-deps && \
#    rm -rf /tmp/*

#ext-xsl
#RUN apk add --no-cache libxslt && \
#    apk add --no-cache --virtual .build-deps libxslt-dev && \
#    docker-php-ext-install xsl  && \
#    apk del .build-deps && \
#    rm -rf /tmp/*

## xdebug
#RUN apk add --no-cache --virtual .build-deps autoconf g++ make linux-headers && \
#    pecl install xdebug-3.2.1 && \
#    docker-php-ext-enable xdebug && \
#    apk del .build-deps && \
#    rm -rf /tmp/*

# ext-gd
#RUN apk add --no-cache libpng libjpeg-turbo libwebp freetype && \
#    apk add --no-cache --virtual .build-deps libpng-dev libjpeg-turbo-dev libwebp-dev freetype-dev && \
#    docker-php-ext-configure gd --with-jpeg --with-webp --with-freetype && \
#    docker-php-ext-install gd && \
#    apk del .build-deps && \
#    rm -rf /tmp/*

# ext-redis
#RUN apk add --no-cache --virtual .build-deps autoconf g++ make &&\
#    pecl install redis-6.2.0 &&\
#    docker-php-ext-enable redis &&\
#    apk del .build-deps

# Composer
COPY --from=composer:2.10 /usr/bin/composer /usr/local/bin/composer