name: Composer

on:
  pull_request:
    branches: [ 'main' ]

jobs:
  validate:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/php:${{matrix.php_version}}
    strategy:
      matrix:
        php_version: [ '8.3','8.4','8.5' ]
    steps:
      - uses: actions/checkout@v4
      - name: Run check
        run: composer validate
